### PR TITLE
Fixed init issue with shutdown of rust app

### PR DESCRIPTION
**Pull request by gahooa**

### CODE REVIEW

**Comment by DILECPEDO** [comment]
Thanks for the collaboration, what does `init` do and solve in this case?

**Comment by gahooa** [comment]
What init does is implements proper signal catching so that the process
will respond to SIGTERM and not hang on shutdown.

Alternative is to have proper signal handling in app (rocket may already)
but CMD must use the ["json", "syntax"] so /bin/sh is not used as a wrapper.

**Comment by DILECPEDO** [comment]
So `init` is to gracefully let a process terminate? by the way all object have a trait known `Drop` which is called when the program is exited or an object goes out of scope. So rocket may already have an implementation for it.

**Comment by gahooa** [comment]
@DILECPEDO this is what it actually does:
It installs this as the actual executable in the container.  https://github.com/krallin/tini

If you noticed, `docker compose down` was taking 10.3 seconds.  It starts by sending SIGTERM and if that does not stop the process it sends SIGKILL.  

There are two options for handling this:

**0. Wrong way:  `CMD /path/to/rust/binary`**
The reason this is wrong is because it actually runs `/bin/sh` as a wrapper.

**1. Right way: `CMD ["/path/to/rust/binary"]**
This is right because docker will not wrap it in `/bin/sh`

**2. Right way: `init: true`**
This is right because `tini` will be used to wrap the binary and implement proper signal handling

**Comment by DILECPEDO** [comment]
I understand, is it the same even tho we are using `ENTRYPOINT`?

**Pull request closed without merging**
